apiVersion: v1
kind: Service
metadata:
  name: {{ include "airllm.fullname" . }}
  labels:
    {{- include "airllm.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.app.service.type }}
  selector:
    {{- include "airllm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
