apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airllm.serviceAccountName" . }}
  labels:
    {{- include "airllm.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
